server:
  port: 8081
rpc:
  config:
    consumer:
      # zookeeper server
      registryAddress: 8.130.123.59:2181
      # registry center type, zookeeper/nacos/apoll/etcd/eureka
      registryType: zookeeper
      loadBalanceType: zkconsistenthash
      # proxy type/javassist/jdk
      proxy: cglib
      # version
      version: 1.0.0
      # group
      group: lh
      serializationType: protostuff
      # timeout
      timeout: 30000
      # async
      async: false
      # oneway
      oneway: false
      # heartbeatInterval
      heartbeatInterval: 30000
      # scanNotActiveChannelInterval
      scanNotActiveChannelInterval: 60000
      # retryInterval
      retryInterval: 1000
      # retryTimes
      retryTimes: 3