server:
  port: 8081

rpc:
  config:
    consumer:
      registryAddress: 8.130.123.59:2181
      registryType: zookeeper
      loadBalanceType: zkconsistenthash
      proxy: cglib
      version: 1.0.0
      group: lh
      serializationType: protostuff
      timeout: 30000
      async: false
      oneway: false
      heartbeatInterval: 30000
      scanNotActiveChannelInterval: 60000
      retryInterval: 1000
      retryTimes: 3